upstream_project_url: https://github.com/cockpit-project/subscription-manager-cockpit
# enable notification of failed downstream jobs as issues
issue_repository: https://github.com/cockpit-project/subscription-manager-cockpit
specfile_path: subscription-manager-cockpit.spec
upstream_package_name: subscription-manager-cockpit
downstream_package_name: subscription-manager-cockpit
# use the nicely formatted release description from our upstream release, instead of git shortlog
copy_upstream_release_description: true

actions:
  post-upstream-clone: make subscription-manager-cockpit.spec
  create-archive:
    - bash -c 'echo "TOMDEBUG"'
    - bash -c 'echo PACKIT_UPSTREAM_PACKAGE_NAME=${PACKIT_UPSTREAM_PACKAGE_NAME}'
    - bash -c 'echo PACKIT_PROJECT_VERSION=${PACKIT_PROJECT_VERSION}'
    - bash -c 'echo PACKIT_PROJECT_NAME_VERSION=${PACKIT_PROJECT_NAME_VERSION}'
    - bash -c 'echo MAKE_VERSION=$(make print-version)'

srpm_build_deps:
  - make
  - npm

jobs:
  - job: tests
    trigger: pull_request
    targets: &test_targets
      fedora-42: {}
      fedora-43: {}
      fedora-latest-stable-aarch64: {}
      fedora-rawhide: {}
      centos-stream-9-x86_64:
        distros: ["centos-stream-9", "CentOS-Stream-9-image-mode"]
      centos-stream-9-aarch64: {}
      centos-stream-10-x86_64:
        distros: ["centos-stream-10", "CentOS-Stream-10-image-mode"]

  - job: copr_build
    trigger: pull_request
    targets: *test_targets

  - job: copr_build
    trigger: release
    owner: "@cockpit"
    project: "cockpit-preview"
    preserve_project: True
    actions:
      post-upstream-clone: make subscription-manager-cockpit.spec
      # HACK: tarball for releases (copr_build, koji, etc.), copying spec's Source0; this
      # really should be the default, see https://github.com/packit/packit-service/issues/1505
      create-archive:
        - sh -exc "curl -L -O https://github.com/cockpit-project/subscription-manager-cockpit/releases/download/${PACKIT_PROJECT_VERSION}/${PACKIT_PROJECT_NAME_VERSION}.tar.xz"
        - sh -exc "ls ${PACKIT_PROJECT_NAME_VERSION}.tar.xz"

  - job: copr_build
    trigger: commit
    branch: "^main$"
    owner: "@cockpit"
    project: "main-builds"
    preserve_project: True

  - job: propose_downstream
    trigger: release
    dist_git_branches:
      - fedora-development
      - fedora-42
      - fedora-43

  - job: koji_build
    trigger: commit
    dist_git_branches:
      - fedora-development
      - fedora-42
      - fedora-43

  - job: bodhi_update
    trigger: commit
    dist_git_branches:
      # rawhide updates are created automatically
      - fedora-42
      - fedora-43
